services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - '5001:5000'
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
